// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model

// User is the golang structure for table user.
type User struct {
	Id       string `orm:"id,primary" json:"id"`       // 用户id（主键）
	Username string `orm:"username"   json:"username"` // 用户名称
	RealName string `orm:"real_name"  json:"realName"` // 用户真实名称
	RoleId   int    `orm:"role_id"    json:"roleId"`   // 用户角色，1表示普通用户
	Password string `orm:"password"   json:"password"` // 用户密码
	Phone    string `orm:"phone"      json:"phone"`    // 用户电话
	Balance  uint64 `orm:"balance"    json:"balance"`  // 用户余额
	Status   int    `orm:"status"     json:"status"`   // 用户状态，1表示正常，0表示暂停
	Created  string `orm:"created"    json:"created"`  // 创建时间
	Updated  string `orm:"updated"    json:"updated"`  // 更新时间
}

// Address is the golang structure for table address.
type Address struct {
	Id              uint64 `orm:"id,primary"       json:"id"`              // 地址id
	UserId          string `orm:"user_id"          json:"userId"`          // 用户id
	Name            string `orm:"name"             json:"name"`            // 收货人姓名
	Mobile          string `orm:"mobile"           json:"mobile"`          // 手机号
	PostalCode      int    `orm:"postal_code"      json:"postalCode"`      // 邮政编码
	Province        string `orm:"province"         json:"province"`        // 省
	City            string `orm:"city"             json:"city"`            // 城市
	District        string `orm:"district"         json:"district"`        // 区/县
	DetailedAddress string `orm:"detailed_address" json:"detailedAddress"` // 详细地址
	IsDefault       int    `orm:"is_default"       json:"isDefault"`       // 1为默认，0为非默认
	Created         string `orm:"created"          json:"created"`         // 创建时间
	Updated         string `orm:"updated"          json:"updated"`         // 更新时间
}

// Category is the golang structure for table category.
type Category struct {
	Id       uint64 `orm:"id,primary" json:"id"`       // 类目id
	Name     string `orm:"name"       json:"name"`     // 类目名称
	ParentId int64  `orm:"parent_id"  json:"parentId"` // 父级类目id
	Level    int    `orm:"level"      json:"level"`    // 类目层级
	Sort     int    `orm:"sort"       json:"sort"`     // 类目排序
	Created  string `orm:"created"    json:"created"`  // 创建时间
	Updated  string `orm:"updated"    json:"updated"`  // 更新时间
}

// Order is the golang structure for table order.
type Order struct {
	Id          uint64  `orm:"id,primary"   json:"id"`          // 订单id
	ProductItem string  `orm:"product_item" json:"productItem"` // 商品项
	TotalPrice  float64 `orm:"total_price"  json:"totalPrice"`  // 合计
	Status      string  `orm:"status"       json:"status"`      // 订单状态
	AddressId   int64   `orm:"address_id"   json:"addressId"`   // 地址id
	UserId      string  `orm:"user_id"      json:"userId"`      // 用户id
	NickName    string  `orm:"nick_name"    json:"nickName"`    // 用户昵称
	Created     string  `orm:"created"      json:"created"`     // 创建时间
	Updated     string  `orm:"updated"      json:"updated"`     // 更新时间
}

// Product is the golang structure for table product.
type Product struct {
	Id                uint64  `orm:"id,primary"         json:"id"`                // 商品编号
	CategoryId        int64   `orm:"category_id"        json:"categoryId"`        // 类目编号
	Title             string  `orm:"title"              json:"title"`             // 商品标题
	Description       string  `orm:"description"        json:"description"`       // 商品描述
	Price             float64 `orm:"price"              json:"price"`             // 商品价格
	Amount            int     `orm:"amount"             json:"amount"`            // 商品数量
	Sales             int     `orm:"sales"              json:"sales"`             // 商品销量
	MainImage         string  `orm:"main_image"         json:"mainImage"`         // 商品主图
	Delivery          string  `orm:"delivery"           json:"delivery"`          // 商品发货
	Assurance         string  `orm:"assurance"          json:"assurance"`         // 商品保障
	Name              string  `orm:"name"               json:"name"`              // 商品名称
	Weight            float64 `orm:"weight"             json:"weight"`            // 商品重量
	Brand             string  `orm:"brand"              json:"brand"`             // 商品品牌
	Origin            string  `orm:"origin"             json:"origin"`            // 商品产地
	ShelfLife         int     `orm:"shelf_life"         json:"shelfLife"`         // 商品保质期
	NetWeight         float64 `orm:"net_weight"         json:"netWeight"`         // 商品净含量
	UseWay            string  `orm:"use_way"            json:"useWay"`            // 使用方式
	PackingWay        string  `orm:"packing_way"        json:"packingWay"`        // 包装方式
	StorageConditions string  `orm:"storage_conditions" json:"storageConditions"` // 存储条件
	DetailImage       string  `orm:"detail_image"       json:"detailImage"`       // 详情图片
	Status            int     `orm:"status"             json:"status"`            // 商品状态
	Created           string  `orm:"created"            json:"created"`           // 创建时间
	Updated           string  `orm:"updated"            json:"updated"`           // 更新时间
}
