# HTTP Server
[server]
	Address     = ":8199"
	ServerRoot  = "public"
	ServerAgent = "sfmall"
	LogPath     = "/tmp/log/sfmall/server"

# Logger.
[logger]
    Path        = "/tmp/log/sfmall"
    Level       = "all"
    Stdout      = true

# Template.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  =  ["{{", "}}"]

# Database.
[database]
    link  = "mysql:root:123456@tcp(127.0.0.1:33060)/sfmall"
    debug = true
    # Database logger.
    [database.logger]
        Path   = "/tmp/log/sfmall/sql"
        Level  = "all"
        Stdout = true

# GF-CLI工具配置
[gfcli]
    # 自定义DAO生成配置(默认是读取database配置)
    [[gfcli.gen.dao]]
        link   = "mysql:root:123456@tcp(127.0.0.1:33060)/sfmall"
        tables = "user,address,category,order,product"

jwt:
  ExpireTime: 60
  RefreshTime: 480
  SignKey: sfmall
  Realm: sfmall zone
  IdentityKey: id
  TokenLookup: 'header: Authorization, query: token, cookie: jwt'
  TokenHeadName: Bearer