// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sfmall/app/dao/internal"
)

// addressDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type addressDao struct {
	*internal.AddressDao
}

var (
	// Address is globally public accessible object for table address operations.
	Address = addressDao{
		internal.NewAddressDao(),
	}
)

// Fill with you ideas below.
