// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sfmall/app/dao/internal"
)

// productDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type productDao struct {
	*internal.ProductDao
}

var (
	// Product is globally public accessible object for table product operations.
	Product = productDao{
		internal.NewProductDao(),
	}
)

// Fill with you ideas below.
