// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
)

// CategoryDao is the manager for logic model data accessing and custom defined data operations functions management.
type CategoryDao struct {
	Table   string          // Table is the underlying table name of the DAO.
	Group   string          // Group is the database configuration group name of current DAO.
	Columns CategoryColumns // Columns is the short type for Columns, which contains all the column names of Table for convenient usage.
}

// CategoryColumns defines and stores column names for table category.
type CategoryColumns struct {
	Id       string // 类目id
	Name     string // 类目名称
	ParentId string // 父级类目id
	Level    string // 类目层级
	Sort     string // 类目排序
	Created  string // 创建时间
	Updated  string // 更新时间
}

//  categoryColumns holds the columns for table category.
var categoryColumns = CategoryColumns{
	Id:       "id",
	Name:     "name",
	ParentId: "parent_id",
	Level:    "level",
	Sort:     "sort",
	Created:  "created",
	Updated:  "updated",
}

// NewCategoryDao creates and returns a new DAO object for table data access.
func NewCategoryDao() *CategoryDao {
	return &CategoryDao{
		Group:   "default",
		Table:   "category",
		Columns: categoryColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *CategoryDao) DB() gdb.DB {
	return g.DB(dao.Group)
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *CategoryDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.Table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *CategoryDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
